const Employees=[
    {
        id:1,
        image:"../Images/bighead1.svg",
        Name:"Niharika",
        Position:"Web Developer"
    },
    {
        id:2,
        image:"../Images/bighead2.svg",
        Name:"Joeseph",
        Position:"Supplier"
    },
    {
        id:3,
        image:"../Images/bighead3.svg",
        Name:"Lily",
        Position:"Manager"
    },
    {
        id:4,
        image:"../Images/bighead4.svg",
        Name:"Samantha",
        Position:"Decorator"
    },
    {
        id:5,
        image:"../Images/bighead5.svg",
        Name:"Feyre",
        Position:"Artist"
    },
    {
        id:6,
        image:"../Images/bighead6.svg",
        Name:"Elsa",
        Position:"Accountant"
    },
    {
        id:7,
        image:"../Images/bighead1.svg",
        Name:"Rose",
        Position:"Designer"
    },
    {
        id:8,
        image:"../Images/bighead2.svg",
        Name:"Connor",
        Position:"Co-coordinator"
    },
    {
        id:9,
        image:"../Images/bighead5.svg",
        Name:"Shannon",
        Position:"Supplier"
    }
]
export default Employees;